### ISSUE TITLE
The webToken is dead

### ISSUE THREAD

**Issue by Kacper1263** [spencercharest/tidal-api#9]
For few weeks I cant login to Tidal using this API. But I found the problem. The problem is webToken in index.js. I don't know what is wrong but when I fount this token (kgsOOmYk3zShYrNP) on the internet and replace the original token everything starts working again.

I thing we need new token in your GREAT API.

**Comment by spencercharest** [comment]
@Kacper1263 thanks for the heads up! I saw that the e2e tests were failing but haven't had any time to look into it. I switched the token and everything seems good. I just published `1.7.1` to NPM with this fix.
